# Site settings
name: Jin
email: sn98192411@gmail.com
author: 
url: http://www.Jin-Nyy.github.io
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/jin-nyy/
baseurl: ""
description: Actually, less is more!
meta_description: ""
motto: It's our wits that make us men.
banner: ""。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: jin-nyy

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

